// Generates what the browser and the README need from the dimension modules:
//   web/generated/fields.ts    SchoolRecord type (one property per declared field)
//   web/generated/registry.ts  imports every dimensions/*/web.ts
//   README.md                  the "Data sources" table, between marker comments
// None of it is hand-edited. The two generated files are git-ignored.

import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { FieldDef } from './dimension.ts';
import { GENERATED_DIR, ROOT } from './paths.ts';
import type { LoadedDimension } from './registry.ts';

/** Names a dimension's web.ts may export. A typo (`mode` for `modes`) would otherwise be silently ignored. */
export const WEB_EXPORTS = ['modes', 'filters', 'popupSections', 'popupRows', 'popupTags', 'sourceNotes', 'extensions'];

const HEADER = '// Generated by `npm run generate` (also run by build and typecheck). Do not edit.\n';

async function writeIfChanged(file: string, content: string): Promise<void> {
  if (existsSync(file) && (await readFile(file, 'utf-8')) === content) return;
  await mkdir(join(file, '..'), { recursive: true });
  await writeFile(file, content);
}

const tsType = (f: FieldDef): string => {
  const base =
    f.type === 'enum' ? f.values.map((v) => JSON.stringify(v)).join(' | ') : f.type === 'number' ? 'number' : f.type === 'boolean' ? 'boolean' : 'string';
  return f.nullable === false ? base : `${base} | null`;
};

export function fieldsSource(order: LoadedDimension[]): string {
  const lines: string[] = [HEADER, 'export interface SchoolRecord {', '  urn: number;'];
  const meta: string[] = [];
  for (const d of order) {
    for (const [name, f] of Object.entries(d.module.fields)) {
      const doc = [f.label, f.description].filter(Boolean).join('. ');
      lines.push(`  /** ${doc.replaceAll('*/', '* /')} (${d.id}, ${f.placement}) */`, `  ${name}: ${tsType(f)};`);
      meta.push(`  ${name}: { module: ${JSON.stringify(d.id)}, placement: ${JSON.stringify(f.placement)}, label: ${JSON.stringify(f.label)} },`);
    }
  }
  lines.push('}', '', "export const FIELDS: Record<Exclude<keyof SchoolRecord, 'urn'>, { module: string; placement: 'core' | 'mode' | 'detail'; label: string }> = {", ...meta, '};', '');
  return lines.join('\n');
}

export async function registrySource(order: LoadedDimension[]): Promise<string> {
  const web = order.filter((d) => d.hasWeb);
  const camel = (id: string) => id.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  for (const d of web) {
    const text = await readFile(join(d.dir, 'web.ts'), 'utf-8');
    const exported = [...text.matchAll(/^export\s+(?:const|function|let)\s+(\w+)/gm)].map((m) => m[1]);
    const unknown = exported.filter((n) => !WEB_EXPORTS.includes(n));
    if (unknown.length) {
      throw new Error(`dimensions/${d.id}/web.ts exports ${unknown.join(', ')}; allowed exports are ${WEB_EXPORTS.join(', ')}`);
    }
  }
  return [
    HEADER,
    "import type { WebExports } from '../toolkit.ts';",
    ...web.map((d) => `import * as ${camel(d.id)} from '../../dimensions/${d.id}/web.ts';`),
    '',
    'export const webModules: { id: string; web: WebExports }[] = [',
    ...web.map((d) => `  { id: ${JSON.stringify(d.id)}, web: ${camel(d.id)} },`),
    '];',
    '',
  ].join('\n');
}

export const README_START = '<!-- sources:start (generated from dimensions/*/source.ts by `npm run generate`; do not edit) -->';
export const README_END = '<!-- sources:end -->';

export function sourcesTable(order: LoadedDimension[]): string {
  const rows = order.flatMap((d) =>
    d.sources.map((s) => {
      const cell = (t: string) => t.replaceAll('|', '\\|');
      const notes = [`Updated ${s.updated}.`, s.notes].filter(Boolean).join(' ');
      return `| [${cell(s.describe)}](${s.homepage}), ${cell(s.publisher)} (${cell(s.licence)}) | ${cell(s.usedFor ?? '')} | ${cell(notes)} |`;
    }),
  );
  return ['| Source | Used for | Notes |', '| --- | --- | --- |', ...rows].join('\n');
}

export async function generateAll(order: LoadedDimension[]): Promise<void> {
  await writeIfChanged(join(GENERATED_DIR, 'fields.ts'), fieldsSource(order));
  await writeIfChanged(join(GENERATED_DIR, 'registry.ts'), await registrySource(order));

  const readme = join(ROOT, 'README.md');
  const text = await readFile(readme, 'utf-8');
  const start = text.indexOf('<!-- sources:start');
  const end = text.indexOf(README_END);
  if (start < 0 || end < start) {
    throw new Error(`${relative(ROOT, readme)} needs the ${README_START} ... ${README_END} markers around the Data sources table`);
  }
  await writeIfChanged(readme, `${text.slice(0, start)}${README_START}\n${sourcesTable(order)}\n${text.slice(end)}`);
}
